param(
    [string]$ApiBase = "",
    [switch]$StartIfDown
)

$ErrorActionPreference = "Stop"
$projectRoot = Split-Path -Parent $MyInvocation.MyCommand.Path
Set-Location $projectRoot

function Normalize-FinMarkApiBaseUrl {
    param([string]$Value)
    if (-not $Value) { return "" }
    $clean = $Value.Trim().TrimEnd("/")
    if ($clean.EndsWith("/api/v1")) { return $clean }
    if ($clean.EndsWith("/api")) { return "$clean/v1" }
    return "$clean/api/v1"
}

function Add-FinMarkCandidate {
    param(
        [System.Collections.ArrayList]$Candidates,
        [string]$Url
    )
    $normalized = Normalize-FinMarkApiBaseUrl -Value $Url
    if ($normalized -and -not $Candidates.Contains($normalized)) {
        [void]$Candidates.Add($normalized)
    }
}

function Test-FinMarkGateway {
    param([string]$BaseUrl)
    try {
        $health = Invoke-RestMethod -Method Get -Uri "$BaseUrl/health" -TimeoutSec 3
        if ($health) { return $true }
    }
    catch {
        return $false
    }
    return $false
}

function Get-FinMarkApiBaseCandidates {
    $candidates = New-Object System.Collections.ArrayList

    if ($ApiBase) {
        Add-FinMarkCandidate -Candidates $candidates -Url $ApiBase
    }

    $apiBaseFile = Join-Path $projectRoot ".microservices\api-base-url.txt"
    if (Test-Path $apiBaseFile) {
        $value = (Get-Content $apiBaseFile -ErrorAction SilentlyContinue | Select-Object -First 1)
        Add-FinMarkCandidate -Candidates $candidates -Url $value
    }

    $pidFile = Join-Path $projectRoot ".microservices\local-pids.csv"
    if (Test-Path $pidFile) {
        try {
            $rows = Import-Csv $pidFile
            foreach ($row in $rows) {
                if ($row.name -like "local-api-gateway*" -and $row.port) {
                    Add-FinMarkCandidate -Candidates $candidates -Url "http://127.0.0.1:$($row.port)/api/v1"
                }
            }
        }
        catch { }
    }

    $frontendEnv = Join-Path $projectRoot "frontend\.env.local"
    if (Test-Path $frontendEnv) {
        $line = Get-Content $frontendEnv -ErrorAction SilentlyContinue | Where-Object { $_ -match '^VITE_API_BASE_URL=' } | Select-Object -First 1
        if ($line) {
            Add-FinMarkCandidate -Candidates $candidates -Url (($line -replace '^VITE_API_BASE_URL=', '').Trim())
        }
    }

    Add-FinMarkCandidate -Candidates $candidates -Url "http://127.0.0.1:8000/api/v1"
    for ($port = 18000; $port -le 18030; $port++) {
        Add-FinMarkCandidate -Candidates $candidates -Url "http://127.0.0.1:$port/api/v1"
    }

    return $candidates
}

function Get-FinMarkRunningApiBaseUrl {
    $candidates = Get-FinMarkApiBaseCandidates
    foreach ($candidate in $candidates) {
        if (Test-FinMarkGateway -BaseUrl $candidate) {
            return $candidate
        }
    }
    return ""
}

function Set-FinMarkFrontendApiBaseUrl {
    param([string]$BaseUrl)
    $frontendDir = Join-Path $projectRoot "frontend"
    if (-not (Test-Path $frontendDir)) { return }
    $envLocal = Join-Path $frontendDir ".env.local"
    $content = @"
# Auto-generated by FinMark verification/startup scripts.
VITE_API_BASE_URL=$BaseUrl
VITE_REQUEST_TIMEOUT_MS=15000
VITE_PRODUCT_CACHE_TTL_MS=60000
"@
    Set-Content -Path $envLocal -Value $content -Encoding UTF8
}

function Resolve-FinMarkListResponse {
    param($Value)
    if ($null -eq $Value) { return @() }
    $propertyNames = @($Value.PSObject.Properties | ForEach-Object { $_.Name })
    if ($propertyNames -contains "items") { return @($Value.items) }
    if ($propertyNames -contains "data") { return @($Value.data) }
    return @($Value)
}

function Invoke-FinMarkJson {
    param(
        [string]$Method,
        [string]$Uri,
        [hashtable]$Headers = $null,
        [string]$ContentType = $null,
        $Body = $null
    )
    try {
        $params = @{
            Method = $Method
            Uri = $Uri
            TimeoutSec = 20
        }
        if ($Headers) { $params.Headers = $Headers }
        if ($ContentType) { $params.ContentType = $ContentType }
        if ($null -ne $Body) { $params.Body = $Body }
        return Invoke-RestMethod @params
    }
    catch {
        Write-Host "Request failed: $Method $Uri" -ForegroundColor Red
        if ($_.Exception.Response) {
            try {
                $reader = New-Object System.IO.StreamReader($_.Exception.Response.GetResponseStream())
                $errorBody = $reader.ReadToEnd()
                if ($errorBody) { Write-Host $errorBody -ForegroundColor DarkYellow }
            }
            catch { }
        }
        throw
    }
}

$apiBase = Get-FinMarkRunningApiBaseUrl

if (-not $apiBase -and $StartIfDown) {
    Write-Host "No running local API gateway was found. Starting local enterprise microservices first..." -ForegroundColor Yellow
    & (Join-Path $projectRoot "start-microservices-local-mysql.ps1")
    Start-Sleep -Seconds 8
    $apiBase = Get-FinMarkRunningApiBaseUrl
}

if (-not $apiBase) {
    Write-Host "Unable to connect to the local API gateway." -ForegroundColor Red
    Write-Host "This usually means the microservices are not running, or frontend\.env.local has a stale fallback port." -ForegroundColor Yellow
    Write-Host "Run these commands:" -ForegroundColor Cyan
    Write-Host "  .\stop-microservices-local.ps1" -ForegroundColor White
    Write-Host "  .\start-microservices-local-mysql.ps1" -ForegroundColor White
    Write-Host "Then use the Gateway health URL printed by the startup script, or run this verifier again with:" -ForegroundColor Cyan
    Write-Host "  .\verify-checkout-admin-order-list.ps1" -ForegroundColor White
    Write-Host "If you want the script to start services automatically, run:" -ForegroundColor Cyan
    Write-Host "  .\verify-checkout-admin-order-list.ps1 -StartIfDown" -ForegroundColor White
    exit 1
}

Set-FinMarkFrontendApiBaseUrl -BaseUrl $apiBase
Write-Host "Testing checkout-to-admin-order-list flow against: $apiBase" -ForegroundColor Cyan

$form = "username=admin%40example.com&password=Admin%4012345"
$tokenResponse = Invoke-FinMarkJson -Method Post -Uri "$apiBase/auth/token" -ContentType "application/x-www-form-urlencoded" -Body $form
$headers = @{ Authorization = "Bearer $($tokenResponse.access_token)" }

$productsResponse = Invoke-FinMarkJson -Method Get -Uri "$apiBase/inventory/products" -Headers $headers
$products = Resolve-FinMarkListResponse -Value $productsResponse
if (-not $products -or $products.Count -lt 1) {
    throw "No inventory products found. Run .\seed-enterprise-mysql.ps1 first."
}

$product = $products[0]
$idempotencyKey = "verify-admin-order-list-$([guid]::NewGuid().ToString('N'))"
$checkoutPayload = @{
    customer_name = "Admin Order List Verification"
    delivery_address = "FinMark Verification Address"
    payment_method = "Cash on Delivery"
    coupon_code = ""
    idempotency_key = $idempotencyKey
    items = @(@{ product_id = [int]$product.id; quantity = 1 })
} | ConvertTo-Json -Depth 8

$checkoutHeaders = $headers.Clone()
$checkoutHeaders["Idempotency-Key"] = $idempotencyKey
$order = Invoke-FinMarkJson -Method Post -Uri "$apiBase/orders/checkout" -Headers $checkoutHeaders -ContentType "application/json" -Body $checkoutPayload
Write-Host "Checkout created order: $($order.order_id)" -ForegroundColor Green

$ordersResponse = Invoke-FinMarkJson -Method Get -Uri "$apiBase/orders?limit=100&search=$($order.order_id)" -Headers $headers
$orders = Resolve-FinMarkListResponse -Value $ordersResponse
$matched = $orders | Where-Object { $_.order_number -eq $order.order_id }

if (-not $matched) {
    Write-Host "Direct /orders lookup did not find the order. Trying compatibility route /database/orders..." -ForegroundColor Yellow
    $ordersResponse = Invoke-FinMarkJson -Method Get -Uri "$apiBase/database/orders?limit=100&search=$($order.order_id)" -Headers $headers
    $orders = Resolve-FinMarkListResponse -Value $ordersResponse
    $matched = $orders | Where-Object { $_.order_number -eq $order.order_id }
}

if (-not $matched) {
    throw "Checkout succeeded, but the order was not returned by Admin order list APIs. Check order service logs."
}

Write-Host "PASS: Admin Manage Order List can read the newly checked-out order: $($matched.order_number)" -ForegroundColor Green

Write-Host "Testing unfiltered Admin Order List, the same request used by the browser..." -ForegroundColor Cyan
try {
    $allOrdersResponse = Invoke-FinMarkJson -Method Get -Uri "$apiBase/orders?limit=100&_ts=$([DateTimeOffset]::UtcNow.ToUnixTimeMilliseconds())" -Headers $headers
    $allOrders = Resolve-FinMarkListResponse -Value $allOrdersResponse
    $unfilteredMatched = $allOrders | Where-Object { $_.order_number -eq $order.order_id }
    if ($unfilteredMatched) {
        Write-Host "PASS: Unfiltered Admin Order List also includes the new order." -ForegroundColor Green
    } else {
        Write-Host "WARNING: Search found the order, but the unfiltered list did not show it in the first 100 rows." -ForegroundColor Yellow
        Write-Host "Open Admin > Orders and search: $($order.order_id)" -ForegroundColor Yellow
    }
}
catch {
    Write-Host "WARNING: The unfiltered Admin Order List failed." -ForegroundColor Yellow
    Write-Host "Most common cause: old seeded rows have lowercase status values like paid/completed." -ForegroundColor Yellow
    Write-Host "Run this repair command, then restart services:" -ForegroundColor Cyan
    Write-Host "  .\repair-order-statuses.ps1" -ForegroundColor White
    Write-Host "  .\stop-microservices-local.ps1" -ForegroundColor White
    Write-Host "  .\start-microservices-local-mysql.ps1" -ForegroundColor White
}

Write-Host "Open Admin Dashboard > Orders > Refresh. The order should appear in the list." -ForegroundColor Green
