#
# Assigned to: Conrado
# Task: Backend Task 1 - Implement User Registration Endpoint (Routes & Controller)
#
# Description:
# This task involves creating the FastAPI route for user registration and defining how it interacts
# with the controller layer.
#
# Deliverables:
# 1. Add a new FastAPI route (e.g., `@router.post("/register")`) to this file.
# 2. This route should:
#    - Accept username (email) and password as input. For this, you should define a Pydantic
#      `UserCreate` request model (e.g., `from pydantic import BaseModel`, `class UserCreate(BaseModel): ...`).
#    - Call a new function in `auth_controller.py` (e.g., `auth_controller.register_new_user()`)
#      with the provided credentials.
#    - Return appropriate HTTP responses based on the registration outcome:
#      - `201 Created` on successful registration (e.g., `{"message": "User registered successfully"}`).
#      - `400 Bad Request` if the username (email) already exists (by catching an exception or checking return from controller).
#      - `422 Unprocessable Entity` for invalid input (Pydantic will handle some of this automatically).
#
# Considerations:
# - Coordinate with Kenneth (Backend Task 2) who will implement the service logic for registration.
# - You will need to import `UserCreate` model and `Response` object if using HTTP 201.
#
#
# Assigned to: Aleczandra
# Task: Backend Task 3 - Enhance Token Structure & Generation
#
# Description:
# This task involves ensuring the `/token` endpoint correctly returns the newly generated structured token
# from the authentication controller. The `token` variable already holds the structured token from the controller.
#
# Deliverables:
# 1. Verify that the `login_for_access_token` function correctly returns the `token` received
#    from `auth_controller.authenticate_user`. This part is already implemented below.
#
# Considerations:
# - The `form_data.username` is passed as the `username` to the controller.
# - This task primarily involves understanding the flow of the token from the controller to the response.
#
from fastapi import APIRouter, Depends, HTTPException, status
from fastapi.security import OAuth2PasswordRequestForm
from pydantic import BaseModel # Needed for UserCreate model
from ..controllers import auth_controller

router = APIRouter()

# Pydantic model for user registration request body
class UserCreate(BaseModel):
    username: str
    password: str

@router.post("/token")
async def login_for_access_token(form_data: OAuth2PasswordRequestForm = Depends()):
    token = auth_controller.authenticate_user(form_data.username, form_data.password)
    if not token:
        raise HTTPException(
            status_code=status.HTTP_401_UNAUTHORIZED,
            detail="Incorrect username or password",
            headers={"WWW-Authenticate": "Bearer"},
        )
    return {"access_token": token, "token_type": "bearer"} # This now returns the token generated by A's task