from ..schemas.shop import Product

PRODUCTS: list[Product] = [
    Product(
        id=1,
        name="FinMark Smart Ledger",
        category="Finance Tools",
        description="A lightweight ledger kit for tracking small-business sales, expenses, and cash flow.",
        price=1499,
        compare_at_price=1899,
        stock=18,
        rating=4.8,
        badge="Best Seller",
        image="📒",
    ),
    Product(
        id=2,
        name="Marketing Launch Pack",
        category="Marketing",
        description="Ready-to-use campaign templates for product launches, retargeting, and weekly reporting.",
        price=2199,
        compare_at_price=2599,
        stock=11,
        rating=4.7,
        badge="Popular",
        image="🚀",
    ),
    Product(
        id=3,
        name="Inventory Starter Bundle",
        category="Operations",
        description="Barcode labels, reorder trackers, and stock movement templates for growing stores.",
        price=1799,
        compare_at_price=None,
        stock=25,
        rating=4.6,
        badge="New",
        image="📦",
    ),
    Product(
        id=4,
        name="Business Analytics Board",
        category="Analytics",
        description="Dashboard widgets for revenue trends, product performance, and conversion monitoring.",
        price=2999,
        compare_at_price=3499,
        stock=8,
        rating=4.9,
        badge="Premium",
        image="📊",
    ),
    Product(
        id=5,
        name="Checkout Optimization Kit",
        category="E-Commerce",
        description="A UX checklist and reporting pack for reducing abandoned carts and improving checkout flow.",
        price=1299,
        compare_at_price=1599,
        stock=16,
        rating=4.5,
        badge="Sale",
        image="🛒",
    ),
    Product(
        id=6,
        name="Customer Care Script Set",
        category="Support",
        description="Reusable response templates for order issues, refunds, shipping delays, and client follow-ups.",
        price=899,
        compare_at_price=None,
        stock=31,
        rating=4.4,
        badge="Starter",
        image="💬",
    ),
]
