# Windows-safe TCP port helper functions for FinMark startup scripts.
# These helpers prevent [WinError 10013] by probing a port before Uvicorn/Nginx tries to bind it.

if ($null -eq $script:FinMarkReservedPorts) {
    $script:FinMarkReservedPorts = @{}
}

if ($null -eq $script:FinMarkPortProbeErrors) {
    $script:FinMarkPortProbeErrors = @{}
}

function Test-FinMarkPortAvailable {
    param(
        [Parameter(Mandatory=$true)][int]$Port,
        [switch]$IgnoreReserved
    )

    if (-not $IgnoreReserved -and $script:FinMarkReservedPorts.ContainsKey([string]$Port)) {
        return $false
    }

    $listener = $null
    try {
        $ipAddress = [System.Net.IPAddress]::Parse("127.0.0.1")
        $listener = [System.Net.Sockets.TcpListener]::new($ipAddress, $Port)
        $listener.Server.SetSocketOption(
            [System.Net.Sockets.SocketOptionLevel]::Socket,
            [System.Net.Sockets.SocketOptionName]::ReuseAddress,
            $false
        )
        $listener.Start()
        return $true
    }
    catch {
        $script:FinMarkPortProbeErrors[[string]$Port] = $_.Exception.Message
        return $false
    }
    finally {
        if ($null -ne $listener) {
            try { $listener.Stop() } catch { }
        }
    }
}

function Get-FinMarkAvailablePort {
    param(
        [Parameter(Mandatory=$true)][int[]]$PreferredPorts,
        [Parameter(Mandatory=$true)][int]$FallbackStart,
        [int]$FallbackEnd = 65000,
        [string]$Label = "service"
    )

    foreach ($port in $PreferredPorts) {
        if (Test-FinMarkPortAvailable -Port $port) {
            $script:FinMarkReservedPorts[[string]$port] = $true
            return $port
        }
        elseif ($script:FinMarkPortProbeErrors.ContainsKey([string]$port)) {
            Write-Host ("Preferred port {0} for {1} is not available: {2}" -f $port, $Label, $script:FinMarkPortProbeErrors[[string]$port]) -ForegroundColor Yellow
        }
        else {
            Write-Host ("Preferred port {0} for {1} is already reserved by this startup script." -f $port, $Label) -ForegroundColor Yellow
        }
    }

    for ($port = $FallbackStart; $port -le $FallbackEnd; $port++) {
        if (Test-FinMarkPortAvailable -Port $port) {
            $script:FinMarkReservedPorts[[string]$port] = $true
            Write-Host ("Using fallback port {0} for {1}." -f $port, $Label) -ForegroundColor Yellow
            return $port
        }
    }

    throw "No available TCP port found for $Label between $FallbackStart and $FallbackEnd."
}

function Set-FinMarkFrontendApiUrl {
    param(
        [Parameter(Mandatory=$true)][string]$ProjectRoot,
        [Parameter(Mandatory=$true)][int]$GatewayPort
    )

    $frontendDir = Join-Path $ProjectRoot "frontend"
    if (-not (Test-Path $frontendDir)) {
        return
    }

    $envLocal = Join-Path $frontendDir ".env.local"
    $apiBaseUrl = "http://127.0.0.1:$GatewayPort/api/v1"
    $content = @"
# Auto-generated by FinMark startup scripts.
# This is needed when Windows blocks port 8000 and the gateway uses a fallback port.
VITE_API_BASE_URL=$apiBaseUrl
VITE_REQUEST_TIMEOUT_MS=15000
VITE_PRODUCT_CACHE_TTL_MS=60000
"@
    Set-Content -Path $envLocal -Value $content -Encoding UTF8
    Write-Host ("Frontend API URL written to frontend\.env.local: {0}" -f $apiBaseUrl) -ForegroundColor Cyan
}

function Show-FinMarkWindowsPortHelp {
    Write-Host "" 
    Write-Host "Windows socket guidance:" -ForegroundColor Cyan
    Write-Host "  - [WinError 10013] usually means a port is blocked, reserved, or protected by Windows/security software." -ForegroundColor White
    Write-Host "  - This script now searches for a safe fallback port automatically." -ForegroundColor White
    Write-Host "  - To inspect Windows excluded ports manually, run:" -ForegroundColor White
    Write-Host "      netsh interface ipv4 show excludedportrange protocol=tcp" -ForegroundColor Gray
    Write-Host "  - To see what is using a specific port, run:" -ForegroundColor White
    Write-Host "      netstat -ano | findstr :8000" -ForegroundColor Gray
    Write-Host "" 
}
